# Generated by Django 3.1.3 on 2021-01-08 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0007_auto_20210102_2205'),
        ('Groups', '0003_group_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='mygroups', to='Profile.Profile'),
        ),
        migrations.AlterField(
            model_name='group',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myowngroups', to='Profile.profile'),
        ),
    ]
