# Generated by Django 3.1.3 on 2021-01-11 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(default='Clups/clup.png', upload_to='Clups/')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_team_score', models.CharField(max_length=2)),
                ('right_team_score', models.CharField(max_length=2)),
                ('lefteam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leftt_team', to='Homepage.clup')),
                ('rightteam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='right_team', to='Homepage.clup')),
            ],
        ),
    ]
