# Generated by Django 3.1.3 on 2021-01-11 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='lefteam',
            new_name='leftteam',
        ),
    ]
