# Generated by Django 3.1.3 on 2021-01-11 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0002_auto_20210111_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='leftteam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='left_team', to='Homepage.clup'),
        ),
    ]
