# Generated by Django 3.1.3 on 2021-01-12 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0003_auto_20210112_0003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='leftteam',
        ),
        migrations.RemoveField(
            model_name='match',
            name='rightteam',
        ),
        migrations.DeleteModel(
            name='Clup',
        ),
        migrations.DeleteModel(
            name='Match',
        ),
    ]
