# Generated by Django 3.1.3 on 2020-12-18 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_auto_20201217_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/avatar.png', upload_to='avatars/'),
        ),
    ]
